version: '3'

services:
  fastapi:
    build:
      context: .               # Path to the directory containing the Dockerfile for FastAPI
    ports:
      - "8000:80"             # Map host port 8000 to container port 80
    depends_on:
      - mongodb            # Define dependencies on other services

  mongodb:
    image: mongo:latest       # Use the official MongoDB image
    ports:
      - "27017:27017"         # Map host port 27017 to container port 27017
    volumes:
      - ./mongodb-data:/data/db # Mount a volume for data persistence

  # Add more services (e.g., DHCP microservices) as needed
